spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.96.79.23:3306/sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 47.96.79.23
    port: 5672
    username: admin
    password: admin
  redis:
    host: 47.96.79.23
    port: 6379
  jpa:
    show-sql: true
